-- MySQL Script generated by MySQL Workbench
-- Thu 05 Sep 2024 05:18:56 PM +08
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema math-wizz
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema math-wizz
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `math-wizz` ;
USE `math-wizz` ;

-- -----------------------------------------------------
-- Table `math-wizz`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `math-wizz`.`user` (
  `id` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `is_admin` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `math-wizz`.`room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `math-wizz`.`room` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_room_1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_room_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `math-wizz`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `math-wizz`.`score`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `math-wizz`.`score` (
  `id` INT NOT NULL,
  `score` BIGINT(11) NOT NULL,
  `user_id` INT NOT NULL,
  `room_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_score_1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_score_2_idx` (`room_id` ASC) VISIBLE,
  CONSTRAINT `fk_score_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `math-wizz`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_score_2`
    FOREIGN KEY (`room_id`)
    REFERENCES `math-wizz`.`room` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
